### ISSUE TITLE
Start forwarding on app startup

### ISSUE THREAD

**Issue by yannickglt** [elixsr/FwdPortForwardingApp#1]
First, thanks for this amazing app!
Is it possible to start the port forwarding on Android startup or on the app startup? It could be an option in the settings.
It would be really helpful!

**Comment by odonnellc** [comment]
Hey Yannick, thanks, your support means a lot to us!

As for the active on startup, that's absolutely something we'll look into adding, you should hopefully see it along with a few bug fixes in an upcoming update :).

**Comment by fma965** [comment]
any update?

**Comment by niallmcs** [comment]
Hi guys,

There should be an update available, in the settings, you should find an option to start forwarding when your phone boots up.

Hope that helps,
Niall
