### ISSUE TITLE
Apache can't listen 

### ISSUE THREAD

**Issue by kcubeterm** [elixsr/FwdPortForwardingApp#23]
I have made a localhost Apache server on port 8080, and i forwarded it on public IP with port 8080, no problem while setup, but when i want to access it from browser, http://public_ip:8080
It doesn't show content, site work perfectly on localhost

**Comment by ChillVibesMushroom** [comment]
> I have made a localhost Apache server on port 8080, and i forwarded it on public IP with port 8080, no problem while setup, but when i want to access it from browser, http://public_ip:8080 It doesn't show content, site work perfectly on localhost

Alternative would be ngrok but if you managed to make this work please explain maybe try port forward * 80 maybe
